apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: workspace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/<ORG>/<REPO>-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: FRONTEND_URL
              value: "https://<DOMAIN>"
            - name: AI_CLI
              value: "claude-code"
            - name: MAX_CHARS
              value: "12000"
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SLACK_SIGNING_SECRET
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SLACK_BOT_TOKEN
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: API_KEY
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: workspace
spec:
  selector:
    app: backend
  ports:
    - port: 3001
      targetPort: 3001
